# Generated by Django 5.1.4 on 2024-12-14 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safekey', '0002_alter_usuario_email_alter_usuario_senha'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Professor', 'Professor'), ('Aluno', 'Aluno')], default='Aluno', max_length=13),
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safekey.usuario')),
            ],
        ),
    ]
