# Generated by Django 5.1.4 on 2024-12-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safekey', '0003_usuario_tipo_tipousuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipousuario',
            name='tipo',
            field=models.CharField(default='Aluno', max_length=13),
        ),
    ]
