# Generated by Django 5.1.4 on 2024-12-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safekey', '0004_tipousuario_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipousuario',
            name='tipo',
            field=models.CharField(max_length=13),
        ),
    ]
