# Generated by Django 5.1.4 on 2024-12-14 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safekey', '0005_alter_tipousuario_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipousuario',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='tipousuario',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='safekey.usuario'),
        ),
    ]
