# Generated by Django 5.1.4 on 2025-01-08 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safekey', '0006_remove_tipousuario_tipo_alter_tipousuario_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipousuario',
            name='usuario',
        ),
        migrations.AddField(
            model_name='tipousuario',
            name='tipo',
            field=models.CharField(default='teste', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safekey.tipousuario'),
        ),
    ]
