# Generated by Django 5.1.4 on 2025-01-22 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safekey', '0007_remove_tipousuario_usuario_tipousuario_tipo_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TipoUsuario',
            new_name='TypeUser',
        ),
        migrations.RenameModel(
            old_name='Usuario',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='typeuser',
            old_name='tipo',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='senha',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='tipo',
            new_name='type',
        ),
    ]
