# Generated by Django 5.1.4 on 2025-01-24 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safekey', '0008_rename_tipousuario_typeuser_rename_usuario_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('block', models.CharField(max_length=10, unique=True)),
                ('floor', models.CharField(max_length=10, unique=True)),
                ('type', models.CharField(max_length=15, unique=True)),
                ('status', models.CharField(default='Disponivel', editable=False, max_length=20, unique=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='TypeUser',
            new_name='UserType',
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('start_time', models.TimeField(unique=True)),
                ('end_time', models.TimeField(unique=True)),
                ('reason', models.TextField(max_length=200)),
                ('commentary', models.TextField(max_length=200)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safekey.user')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safekey.room')),
            ],
        ),
    ]
