# Generated by Django 5.1.4 on 2025-01-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safekey', '0009_room_rename_typeuser_usertype_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='commentary',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='block',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(default='Disponivel', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.CharField(max_length=15),
        ),
    ]
