# Generated by Django 5.1.4 on 2025-02-07 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safekey', '0010_alter_reservation_commentary_alter_reservation_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_date_schedulling', models.DateField()),
                ('real_start_time', models.TimeField()),
                ('real_end_time', models.TimeField()),
                ('reason', models.TextField(max_length=200)),
                ('commentary', models.TextField(blank=True, max_length=200)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safekey.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safekey.user')),
            ],
        ),
    ]
