# Generated by Django 5.1.4 on 2025-02-07 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safekey', '0011_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='date',
            new_name='date_schedulling',
        ),
    ]
