# Generated by Django 5.1.4 on 2025-02-27 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safekey', '0012_rename_date_reservation_date_schedulling'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='responsible',
            field=models.ForeignKey(limit_choices_to={'type__type__in': ['Professor', 'Administrador']}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsible_reservations', to='safekey.user'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Aprovado', 'Aprovado'), ('Recusado', 'Recusado')], default='Aprovado', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='safekey.user'),
        ),
    ]
