# Generated by Django 5.1.4 on 2025-03-09 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safekey', '0015_user_date_joined_user_groups_user_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('Disponivel', 'Disponivel'), ('Reservada', 'Reservada'), ('Ocupado', 'Ocupado')], default='Disponivel', editable=False, max_length=20),
        ),
    ]
