# Generated by Django 5.1.4 on 2025-03-24 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safekey', '0016_alter_room_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='real_end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='real_start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='responsible',
            field=models.ForeignKey(default='NUll', limit_choices_to={'type__type__in': ['Professor', 'Administrador']}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsible_reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('Disponivel', 'Disponivel'), ('Reservada', 'Reservada'), ('Ocupado', 'Ocupado')], default='Disponivel', max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='status_key',
            field=models.CharField(choices=[('Disponivel', 'Disponivel'), ('Retirada', 'Retirada')], default='Disponivel', max_length=20),
        ),
    ]
