# Generated by Django 5.1.4 on 2025-04-03 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safekey', '0017_reservation_real_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='real_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='real_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='responsible',
            field=models.ForeignKey(blank=True, limit_choices_to={'type__type__in': ['Professor', 'Administrador']}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsible_reservations', to=settings.AUTH_USER_MODEL),
        ),
    ]
